### ISSUE TITLE
"size" argument must not be larger than 2147483647

### ISSUE THREAD

**Issue by EasyAsABC123** [ForbesLindesay/sha#19]
Can't sha large files

**Comment by ForbesLindesay** [comment]
Is this sync or async or streaming? What's the stack trace?

**Comment by EasyAsABC123** [comment]
After looking it is getSync, but the issue is likely that you are using
fs.readfilesync which has a 2GB buffer limit in node x64

**Comment by ForbesLindesay** [comment]
I have no intention of changing that. If you need to handle sizes over 2GB, use one of the async methods.

**Comment by EasyAsABC123** [comment]
This issue is node based, unlikely any of the functions will work

**Comment by ForbesLindesay** [comment]
The async methods stream, so likely have a much larger limit. The sync method must load the entire file in memory in one go. The stream method never keeps more than a small chunk of the file in memory at any given moment.
